trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  node_version: 10

steps:
  - template: .azure-pipelines/steps/install-nodejs.yml
  - template: .azure-pipelines/steps/install-dependencies.yml

  - script: yarn check:deps
    displayName: 'Check dependencies'

  - script: yarn check:fmt
    displayName: 'Check if files are formatted'

  - script: yarn lint
    displayName: 'Lint code'
